feat: added contact test data
Sphereon-Opensource/SSI-SDK pull request #126
Opened 2023-09-13 12:17 UTC by sksadjad

2023-09-13 18:28 UTC, nklomp approved these changes

2023-09-13 21:25 UTC, nklomp requested changes
Please make these values more in line with what was used in the Web-walet so we have a bit of a feal what more realistic values look like in the ui

2023-09-14 07:24 UTC, sksadjad commented
@nklomp changed the test values to be inline with previous version of test data

2023-09-15 13:39 UTC, nklomp approved these changes

2023-09-15 13:39 UTC, merged