Added identies to contacts
Sphereon-Opensource/SSI-SDK pull request #128
Opened 2023-09-19 14:34 UTC by sanderPostma

2023-09-19 16:38 UTC, nklomp requested changes
Please use the agent method to generate a didKey for you, then assign the did value to the contact. So we can actually use these DIDs from the agent as well. Also never do PII in DIDs!

didKeyIdentifier = await agent.didManagerCreate() // you might need to set the method if did:key isn't defined as the default method on the agent.

2023-09-19 16:38 UTC, nklomp commented on packages/contact-manager-rest-api/__tests__/agent.ts
> +const generateIdentity = (contact: Record<string, any>) : NonPersistedIdentity => {
Please use the agent method to generate a key and never use PII in DIDs (even though this is not stored on a ledger, never use PII for them)

2023-09-20 11:20 UTC, sanderPostma commented
creating did:ion now
Also includes a fix that Bram made remotely after I ran into a typeorm issue.

2023-09-20 11:38 UTC, nklomp approved these changes

2023-09-20 20:17 UTC, merged