fix: add PhysicalAddress migrations to postgres
Sphereon-Opensource/SSI-SDK pull request #181
Opened 2024-04-10 07:50 UTC by jcmelati

2024-04-10 09:00 UTC, BtencateSphereon requested changes
I don't think we released any products yet that use the migrations to production, so please update the existing migration to include the table. This so we keep the complexity down.

Besides that, please look at the naming conventions we use. and use this PR to sync the changes made for sqlite for postgress so we keep them the same.

https://github.com/Sphereon-Opensource/SSI-SDK/pull/161

2024-04-10 09:20 UTC, BtencateSphereon commented
we do have the mobile wallet in the review process, but since this is using sqlite, i do not think this will impact the needed change for postgres. So i would say it is still safe to update the latest postgres migration, instead of making a new migration file. But we need to double check with @nklomp

2024-04-10 11:01 UTC, nklomp commented
Yeah I am still okay with updating it for sqlite at this point. We are at 0.2 and moved to a completely different kv store forcing users to reonboard anyway. Once we are getting closer to 1.0 we will change of course to have new migration files for every single change

2024-04-11 08:34 UTC, BtencateSphereon commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +      CREATE TABLE "PhysicalAddress" (
is missing a PRIMARY KEY constraint

2024-04-11 10:34 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          "type" varchar(255) NOT NULL,
as per documentation, `varchar` and `character varying(255)` are exactly the same thing
https://www.postgresql.org/docs/current/datatype-character.html

2024-04-11 11:15 UTC, BtencateSphereon commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          "type" varchar(255) NOT NULL,
sure, but we use character varying everywhere, so for consistency use that

2024-04-11 13:59 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
Adjusted as per the code standard.

2024-04-11 13:59 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          "last_updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
Adjusted as per the codebase standard.

2024-04-11 13:59 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          "id" text PRIMARY KEY NOT NULL,
Fixed.

2024-04-11 13:59 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          "type" varchar(255) NOT NULL,
Adjusted as per the indicated code base standard.

2024-04-11 14:00 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +          CONSTRAINT "FK_PhysicalAddressEntity_partyId" FOREIGN KEY ("partyId") REFERENCES "Party" ("id") ON DELETE CASCADE
Fixed.

2024-04-11 14:00 UTC, jcmelati commented on packages/data-store/src/migrations/postgres/1690925872592-CreateContacts.ts
> +      CREATE TABLE "PhysicalAddress" (
Fixed.

2024-04-12 09:59 UTC, BtencateSphereon approved these changes

2024-04-12 10:39 UTC, merged