fixes/SDK-43_hasher-for-sd-jwt
Sphereon-Opensource/SSI-SDK pull request #273
Opened 2024-11-12 14:54 UTC by sanderPostma

Due to crash "Hasher implementation is required to decode SD-JWT" in OpSession

2024-11-12 15:03 UTC, BtencateSphereon requested changes

2024-11-12 15:03 UTC, BtencateSphereon commented on packages/siopv2-oid4vp-op-auth/src/session/OpSession.ts
> +        return sum + ((uvp.verifiableCredential?.length ?? CredentialMapper.isSdJwtDecodedCredential(uvp)) ? 1 : 0)
i feel like something is not right here. 1 this is almost unreadable. 2 is this looking for credentials in a presentation and then when it cannot find any we are like ok, maybe it was a sd-jwt?

this logic is kinda weird?

2024-11-14 14:29 UTC, sanderPostma commented on packages/siopv2-oid4vp-op-auth/src/session/OpSession.ts
> +      this.options.hasher = args.hasher
removed

2024-11-14 14:30 UTC, sanderPostma commented on packages/siopv2-oid4vp-op-auth/src/session/OpSession.ts
> +      this.options.hasher = args.hasher
Iterated, we now have countVCsInAllVPs

2024-11-14 15:14 UTC, BtencateSphereon approved these changes

2024-11-14 15:36 UTC, merged